version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.DataProtection.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: IdentityServer4
    versions:
    - 4.1.1
  - dependency-name: IdentityServer4.EntityFramework
    versions:
    - 4.1.1
  - dependency-name: IdentityServer4.AspNetIdentity
    versions:
    - 4.1.1
