language: csharp
mono: none
sudo: required
services:
    - docker
branches:
    only:
        - master
        - dev
before_script:
    - chmod -R a+x scripts
script:
    - "./scripts/travis-build.sh"
after_success:
    - "./scripts/travis-docker-publish.sh"
notifications:
    email: false
    slack:
        secure: Tif5NTSqlt2kv3oeAFfSfFUdSyxkL/1nVYo4t4JGpfrfBW2sNKJ3tW28fn6JkGuuJvHv4sEtwjDATIa0TIN1bkuokMzlrmz8GIqMY0TXPuhlMUbnBLWjWLAZ0YNsT9tmAiCRSzvgxtzJ0vTwLdtbj1ZOxw7/JVYd6d0EEOttDoI+OgBTf6nViUhxxfTTDcCKEvVV0cBu3vzNw4zHPnC8XTyBG0iYiV0UKR9jiagWbfIK8Ffn3hUexKbbQAMFdpy6uHKoNX1COdr/dNfE2vFyzmahFbkIvvM2y8ipgGjnq8PsNxw22RNmt5ftVPQdKoDoMJ+IllqfUzm5KjKDB/8jekjFVm7llP7LjKj506CEaBFMvOZhCj/Bi8oHdTZLS754ZZ22KsFQNuBIfacXzHWH4jQKm49ldUS4g7l7phsKxmhKEEnC+Gci6knfG3N+kEQ3avU7CqA3oOsoQRK/h6J0HWpTiLlBJX2IxtAH8ISu254KDDOZCHxaXtAdoCUNFnF1q5kwiDMEFIk9eJh0CZjNIGyGWMhmwAzJF5w4KsjEsKjWpZmcKfUxqtsjJL/Vi4YFfJKs01K4YzGSeVnkiMlctc9LmVwm4PcT/LxuL0d6EW6EC3V0BMJRpVqsvb2fpCILU7UyQzZOTqacRVzUIsp9kHj7Zhxfy6l4kiRkPeNu2b0=
        on_pull_requests: false
