version: "3.5"
services:
    postgres:
        image: postgres:11
        container_name: tenants_postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        networks:
            - ranger
        volumes:
            - postgres:/data/db
    # redis:
    #     image: redis
    #     container_name: tenants_redis
    #     ports:
    #         - "6379:6379"
    #     networks:
    #         - ranger
    #     # network_mode: host
    #     volumes:
    #         - redis:/data

networks:
    ranger:
        name: ranger-network
        external: true

volumes:
    postgres:
        driver: local
    redis:
        driver: local
